version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=Developer
      - DB_PASSWORD=123456
      - DB_NAME=MKSdatabase
      - REDIS_HOST=localhost
      - REDIS_PORT=${REDIS_PORT}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: MKSdatabase
  redis:
    container_name: redis-cache
    image: redis:alpine
    environment:
     -  REDIS_USER=redis
     -  REDIS_PASSWORD=redis
     -  REDIS_DB=projeto
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"