version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST: ${DB_HOST}
      - DB_PORT: ${DB_PORT}
      - DB_USERNAME: ${DB_USERNAME}
      - DB_PASSWORD: ${DB_PASSWORD}
      - DB_NAME: ${DB_NAME}
      - REDIS_HOST: ${REDIS_HOST}
      - REDIS_PORT: ${REDIS_PORT}
      - PORT: ${PORT}
      - JWT_SECRET: ${JWT_SECRET}
      - JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_postgres_password_here # Defina a senha do banco de dados Postgres
      POSTGRES_DB: MKSdatabase
